### ISSUE TITLE
Dynmap does not update via the plugin updater

### ISSUE THREAD

**Issue by TheBingPlays** [Osiris-Team/AutoPlug-Client#146]
Forwarded from Autoplug discord:
for the life of me I cannot get dynmap to download via the plugin updater
I either get:
failed because of invalid content type: text [using spigot id]
failed because of invalid sub-content type: x-amz-json-1.0 [using bukkit id]
no protocol: webbukkit/dynmap/api/json (There was an api-error for dynmap!)  [github alternative || see photo on how I have it set up]
------------------------------------------------------
I don't know what to do from here, any help is appreciated.
I'm pretty sure I have the regex set wrong or something with GitHub but I'm not sure
![image](https://user-images.githubusercontent.com/32751932/158075271-07eda148-cb3e-4f9c-abdd-dd9ecea2954e.png)
the reason I just have spigot in the asset name is because the assets list looks like this for dynmap
![image](https://user-images.githubusercontent.com/32751932/158075284-6eab5af0-5dfc-485f-b5e2-d9dd87b1706e.png)

**Comment by Osiris-Team** [comment]
This probalby requires changing the algorithm used to find similar files.

**Comment by widget-** [comment]
The Spigot plugin page redirects you to Modrynth which it doesn't look like this will forward to and download. 

The Bukkit page is still hosted on Bukkit and works fine though.

The only issue I saw was that using `.plugin install bukkit31620`, AutoPlug will for some reason save the Spigot ID instead?

But I edited `autoplug/plugins.yml` manually and it worked from that point on:

```yaml
  dynmap: 
    exclude: false
    version: 3.61.10.21.20.1
    latest-version: 3.61.10.21.20.1
    author: mikeprimm
    spigot-id: 0
    bukkit-id: 31620
    ignore-content-type: false
    custom-check-url: 
    custom-download-url: 
    alternatives: 
      github: 
        repo-name: 
        asset-name: 
      jenkins: 
        project-url: 
        artifact-name: 
        build-id: 0
```
