### ISSUE TITLE
Modrinth Support For Plugins

### ISSUE THREAD

**Issue by woliver99** [Osiris-Team/AutoPlug-Client#214]
**Importance:** 7/10

**Problem:**
I tried adding a plugin to auto-update from Modrinth but it doesn't seem to work:

```
FreedomChat:
  exclude: false
  version: 1.3.1
  latest-version: 
  author: Oharass
  spigot-id: 0
  bukkit-id: 0
  ignore-content-type: false
  custom-check-url: https://api.modrinth.com/v2/project/MubyTbnA/version?loaders=[%22paper%22]
  custom-download-url:
```

**Solution:**
Add support for Modrinth or if I'm not doing it correctly show me how
