### ISSUE TITLE
JavaUpdater "Not Found" on Java 21

### ISSUE THREAD

**Issue by SirDank** [Osiris-Team/AutoPlug-Client#229]
<details>
  <summary>Show log</summary>
  
```log
[17-02-2024 ][AP][INFO] JavaUpdater:
[17-02-2024 ][AP][WARN]
url: https://api.adoptium.net/v3/assets/version/%5B21.0.2%2B13.0%5D?architecture=x64&heap_size=normal&image_type=jdk&jvm_impl=hotspot&lts=true&os=windows&page=0&page_size=20&project=jdk&release_type=ga&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse
message: Not Found
json:
null
```
</details>

**Actual**
Not Found

**Steps**
updater.yml
```
updater: 
  java-updater: 
    enable: true
    profile: AUTOMATIC
    version: 21
```

**Related**
https://github.com/Osiris-Team/AutoPlug-Client/issues/223
