### ISSUE TITLE
Problem With Updating Plugins

### ISSUE THREAD

**Issue by Minionguyjpro** [Osiris-Team/AutoPlug-Client#255]
**Importance:** 8/10

**Problem:**
I want to update the plugins in my Minecraft server, but due to this error, it prevents me from doing so:
```
[03-07-2024 15:12:58][AP][WARN] Download of 'ViaBackwards-[5.0.1].jar' failed because of invalid content type: text
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
	at java.base/java.io.File.createNewFile(File.java:1045)
	at com.osiris.jlib.logger.AL.warn(AL.java:133)
	at com.osiris.jlib.logger.AL.warn(AL.java:97)
	at com.osiris.autoplug.client.utils.tasks.UtilsTasks.printResults(UtilsTasks.java:133)
	at com.osiris.autoplug.client.utils.tasks.UtilsTasks.printResultsWhenDone(UtilsTasks.java:65)
```

**Solution:**
Fix this error in the program somewhere, since it looks like some error that needs to be fixed in the program itself.

**Comment by Osiris-Team** [comment]
@Minionguyjpro what does your config for that look like? works for me via github:
![image](https://github.com/Osiris-Team/AutoPlug-Client/assets/59899645/d228078d-8700-4333-aa52-e7a1bc7c8bbb)

**Comment by Minionguyjpro** [comment]
> @Minionguyjpro what does your config for that look like? works for me via github: ![image](https://private-user-images.githubusercontent.com/59899645/345631613-d228078d-8700-4333-aa52-e7a1bc7c8bbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI1MjgsIm5iZiI6MTcyMDEwMjIyOCwicGF0aCI6Ii81OTg5OTY0NS8zNDU2MzE2MTMtZDIyODA3OGQtODcwMC00MzMzLWFhNTItZTdhMWJjN2M4YmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4Mjk3NDE1Njk0MmY5YThkZWViMjUxMzVkNDllNmM3MTBmMGIyN2FkOGVmYWY1YTVlZGUxYWM2Mzg1YTI5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cAqdrGkee2XBzj7bzXnfVoufIUav0w16kKKXxFNBNos)

It's:
```
  ViaBackwards: 
    exclude: false
    version: 4.10.0
    latest-version: 5.0.1
    author: Matsv
    spigot-id: 27448
    bukkit-id: 0
    ignore-content-type: false
    custom-check-url: 
    custom-download-url: 
    alternatives: 
      github: 
        repo-name: 
        asset-name: 
      jenkins: 
        project-url: 
        artifact-name: 
        build-id: 0
    modrinth-id: 
    force-update: false
    ```
