### ISSUE TITLE
Command `version` gives error

### ISSUE THREAD

**Issue by DaniGTA** [Osiris-Team/AutoPlug-Client#54]
**Describe the bug**
i typed version in the consol and i get a error and cant input anything anymore

**To Reproduce**
1. Open AutoPlug with a paper server
2. enter version

**Expected behavior**
Response from the mc console

**Screenshots**
![image](https://user-images.githubusercontent.com/20490672/120085672-6da70d00-c0da-11eb-81bc-44697f61fcfe.png)

**Error-Message:**
```Cannot invoke "com.osiris.autoplug.client.network.online.connections.OnlineConsoleSendConnection.isConnected()" because "com.osiris.autoplug.client.network.online.MainConnection.CON_CONSOLE_SEND" is null```

**Comment by Osiris-Team** [comment]
@DaniGTA Does this also happen for other commands?

**Comment by DaniGTA** [comment]
i found out yes. even . commands not working

**Comment by Osiris-Team** [comment]
> i found out yes. even . commands not working

Can u attach the complete error message. Should be located in /autoplug-logs/warn

**Comment by DaniGTA** [comment]
I think my logs are broken...
![image](https://user-images.githubusercontent.com/20490672/120163613-f799c780-c1f9-11eb-9665-5939a3ea2b5e.png)
[com.osiris.autoplug.client.tasks.updater.plugins.TaskPluginsUpdater().runAtStart().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568829/com.osiris.autoplug.client.tasks.updater.plugins.TaskPluginsUpdater.runAtStart.log)
[com.osiris.autoplug.client.utils.JsonTools().getJsonElement().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568830/com.osiris.autoplug.client.utils.JsonTools.getJsonElement.log)
[com.osiris.dyml.DYReader().parseLine().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568831/com.osiris.dyml.DYReader.parseLine.log)
[java.io.PipedInputStream().read().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568832/java.io.PipedInputStream.read.log)
[No Exception.log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568834/No.Exception.log)
[sun.nio.ch.Net().connect0().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568835/sun.nio.ch.Net.connect0.log)
[sun.nio.ch.NioSocketImpl().timedRead().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568836/sun.nio.ch.NioSocketImpl.timedRead.log)
[sun.nio.fs.WindowsException().translateToIOException().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568838/sun.nio.fs.WindowsException.translateToIOException.log)
[sun.security.ssl.Alert().createSSLException().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568839/sun.security.ssl.Alert.createSSLException.log)
[com.osiris.autoplug.client.console.UserInput().lambda$keyboard$0().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568840/com.osiris.autoplug.client.console.UserInput.lambda.keyboard.0.log)
[com.osiris.autoplug.client.network.online.connections.OnlineConsoleReceiveConnection().close().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568841/com.osiris.autoplug.client.network.online.connections.OnlineConsoleReceiveConnection.close.log)
[com.osiris.autoplug.client.network.online.SecondaryConnection().close().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568842/com.osiris.autoplug.client.network.online.SecondaryConnection.close.log)
[com.osiris.autoplug.client.network.online.SecuredConnection().init().log](https://github.com/Osiris-Team/AutoPlug-Client/files/6568843/com.osiris.autoplug.client.network.online.SecuredConnection.init.log)

**Comment by Osiris-Team** [comment]
@DaniGTA Should be fixed in the latest beta.
Give it a try. Feel free to reopen this if it didn't work for your;)

**Comment by DaniGTA** [comment]
![image](https://user-images.githubusercontent.com/20490672/120235761-0bc1e100-c25b-11eb-821b-b6485c3a210d.png)
Still same error

**Comment by Osiris-Team** [comment]
@DaniGTA But now it seems that you got another error.
That beta release had a lot of other errors nevertheless.
Released another update. Give it a try.
Also, it seems that you haven't got a server key, that's causing the plugin updater errors... Or didn't you want to register?

The original error could be fixed though.

**Comment by DaniGTA** [comment]
i had registered but my config broke and i need to reset it, since then i didnt reenter the key. The error with "Failed to get plugin Information" also there when i had a key.

Console Output: 
![image](https://user-images.githubusercontent.com/20490672/120242852-39f8ee00-c266-11eb-93dc-cd0855001d51.png)

I think the config broke again (i only changed the jars and restart it)

Config looks now like this:

```
autoplug-general-config: 
  server: 
    flags: 
    arguments: 
    flags: 
    arguments: 
    flags: 
    arguments: 
    flags: 
    arguments: 
    # Enter your server-key here. You get the key by registering on https://autoplug.online.
    # The key is essential to perform most of AutoPlugs main operations and it enables remote access from your account.
    # No matter what, keep this key private to ensure your servers security!
    key: abc
    # This is the java version your server will be running on.
    # If you plan to use a specific version of java or you don't have the java path as a System-PATH variable, enter its path here.
    # Otherwise leave it as it is.
    # Example for windows: C:\Progra~1\Java\jdk-14.0.1\bin\java.exe
    java-version: java
```
This config has changed too:

```
autoplug-plugins-config: 
  general: 
    # Keep the plugins entry in this file even after its removal/uninstallation?
    keep-removed: true
  BlueMap: 
    exclude: false
    version: 1.4.2
    latest-version: 
    author: Blue (TBlueF / Lukas Rieger)
    spigot-id: 83557
    bukkit-id: 0
    c-link: 
  CoreProtect: 
    exclude: false
    version: 19.5
    latest-version: 
    author: Intelli
    spigot-id: 8631
    bukkit-id: 0
    c-link: 
  Essentials: 
  floodgate-bukkit: 
  Geyser-Spigot: 
  LoginSecurity: 
  LuckPerms: 
  NoEndermanGrief: 
    exclude: false
    version: 1.14.0.1
    latest-version: 1.14_1.0.2
    author: JoelYahwehOfWar
    spigot-id: 71236
    bukkit-id: 0
    c-link: 
  Plan: 
  ProtocolLib: 
  sleep-most: 
  TreeFeller: 
  ViaBackwards: 
  ViaVersion: 
  Lands: 
    exclude: false
    version: 5.4.6
    latest-version: 
    author: Angeschossen
    spigot-id: 0
    bukkit-id: 0
    c-link: 
  Dynmap-Towny: 
  Essentials: 
  floodgate-bukkit: 
  Geyser-Spigot: 
  LoginSecurity: 
  LuckPerms: 
  NoEndermanGrief: 
    exclude: false
    version: 1.14.0.1
    latest-version: 1.14_1.0.2
    author: JoelYahwehOfWar
    spigot-id: 71236
    bukkit-id: 0
    c-link: 
  Plan: 
  ProtocolLib: 
  sleep-most: 
  TreeFeller: 
  ViaBackwards: 
  ViaVersion: 
  Lands: 
```
(Double entrys ?!?)
