### ISSUE TITLE
Shared plugins/configs across multiple servers.

### ISSUE THREAD

**Issue by Osiris-Team** [Osiris-Team/AutoPlug-Client#80]
Example config section for the general-config for this feature:
```yaml
# Share configurations and plugins through multiple servers
# You can enter the servers absolute path (only needs AutoPlug installed on the 'copy-from' server), or if its located on another
# pc/system you can enter its ip (future feature, requires AutoPlug installed on all servers).
# You can add as many setups as you want, just make sure to name them differently.
shared-servers:
  setup1:
    enable: true
    copy-from: C:/Users/Peter/servers/mc-survival
    paste-to:
      - C:/Users/Peter/servers/mc-survival-extreme
      - C:/Users/Peter/servers/mc-survival-peaceful
    # Share the /plugins folder
    share-plugins: true
    # Share the config files located at the servers root
    share-configs: true
    # Files that should not be shared across the servers.
    excluded-files:
      - ./bukkit.yml
    # Files that should be shared across the servers.
    included-files:
      - ./worlds
  setup2:
    enable: false
    copy-from: C:/Users/Peter/servers/main-hub
    paste-to:
      - C:/Users/Peter/servers/hub2
      - C:/Users/Peter/servers/hub3
    share-plugins: true
    share-configs: true
...
```
Implementation idea:
On startup, the folders from `paste-to` and compared to the folder from `copy-from`, if this folder contains new/updated files these get copied to the `paste-to` folders.
Note that we could also listen for file change events on the general-config.yml and execute the above.
If the user has AutoPlug-Client installed on the `paste-to` servers as well it could be possible to execute `.restart all` or `.stop all` from the `copy-from` server, so the changes take affect, which can be executed from any server from the same setup/shared server group, to restart all servers so the changes take effect.
Another command could be `.restart needed` which will only restart the servers where changes were recently made.
