### ISSUE TITLE
Server updater modify wrong build-id value

### ISSUE THREAD

**Issue by Blank517** [Osiris-Team/AutoPlug-Client#88]
In updater-config.yml if server-updater.alternatives.jenkins.enable is true it modify the value of server-updater.build-id instead of server-updater.alternatives.jenkins.build-id so the jar gets always downloaded at AutoPlug-Client start

```
server-updater: 
    enable: true
    profile: AUTOMATIC
    software: paper
    version: 1.17.1
    build-id: 1391 # <-- Latest version
    alternatives: 
      jenkins: 
        enable: true
        project-url: https://ci.pl3x.net/job/Purpur/
        artifact-name: purpurclip.jar
        artifact-name-similarity: 70
        build-id: 1388 # <-- Manually written to stop v1388 download
```
